[project]
name = 'Multiverse-Communication-Protocol-'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.inter-universe-message-nft]
path = 'contracts/inter-universe-message-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.network-incentive-token]
path = 'contracts/network-incentive-token.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
